### ISSUE TITLE
API errors without more details cause errors

### ISSUE THREAD

**Issue by 0x6C77** [redwebcreation/twitter-stream-api#3]
When creating a new rule the error response from Twitter does not always contain extra details. `$results['errors'][0]['details']` is undefined.

https://github.com/redwebcreation/twitter-stream-api/blob/83e28c13607db1eff8763d276b93963796b157bb/src/Rule.php#L123

**Comment by felixdorn** [comment]
Hello!

Thanks for contributing.

Fixed by 52d5551f21953ae432f0f654f16866365c0fb0ab
