### ISSUE TITLE
PHP Warning:  Uninitialized string offset -1 in /redwebcreation/twitter-stream-api/src/TwitterStream.php on line 45

### ISSUE THREAD

**Issue by devicenull** [redwebcreation/twitter-stream-api#6]
https://github.com/redwebcreation/twitter-stream-api/blob/master/src/TwitterStream.php#L45

It looks like ->read() can return an empty string when a disconnect happens, which causes this to endlessly loop trying to parse an empty string

**Comment by felixdorn** [comment]
Hey! I've just pushed a fix, pretty sure it fixes the issue but I didn't manage to reproduce the issue.

Twitter API is a pain in the a** when it comes to testing it and I haven't found the time to build a proper mock around it.

Feel free to ask for a reopeon.
