### ISSUE TITLE
struggling to understand rules like t`o:`

### ISSUE THREAD

**Issue by jayenne** [redwebcreation/twitter-stream-api#8]
Hi Felix,
I'm sorry but I am really struggling to understand the mechanics of Rules.

I am trying to catch only those tweets: `to:myhandle`
*I don't think I need any word to listen for as `to` is standalone.

I have a working command that listenes for a given string but when I change the rule from `whenHears` to `whenTo` (method below) so I only get tweets that are to a given handle ( using @myhandle at very start of the tweet ) the "to:myhandle" rule doesn't catch any tweets.

Should `to:` work as follows?...
```
public function whenTo(string | array $twitterUserIds, callable $whenTo): self
    {
        $this->rule->to($twitterUserIds);
        $this->onTweet = $whenTo;

        return $this;
    }
```
My startListening() method...
```
public function startListening(Sets $sets = null): void
    {
        // Delete old rules
        Rule::deleteBulk(...Rule::all());
        $this->rule->save();

        foreach ($this->stream->filteredTweets($sets) as $tweet) {
            if (is_null($tweet)) {
                continue;
            }

            call_user_func($this->onTweet, $tweet);
        }
    }
```
I call it from my command...
```
 TwitterStreamingApi::publicStream()
            ->whenTo($handle, function (array $tweet) {
                // log $tweet here;
            })
            ->startListening($sets);
```

would anyome have any pointers on helping me understand this part please?

**Comment by felixdorn** [comment]
Hey!

`to:` matches any Tweet that is in reply to a particular user.
`from:` matches any Tweet from a specific user.

So you probably want to use `from` instead of `to`

**Comment by jayenne** [comment]
No, I need to: for this project. It’s a bot to process member requests.

I haven’t managed to get to: working and so currently use whenHeres(myHandle,…) and check for myHandle == in_reply_to_user_id but this seems like more work for my listener than letting the api only serve those with ‘to:’

*if I understand correctly that to: will tell Twitter to only serve those tweets where @myHandle is the first word of any tweet (an implicit reply)
Regards,
Jayenne

On 17 Sep 2021, at 11:05, Félix Dorn ***@***.***> wrote:

﻿

Hey!

to: matches any Tweet that is in reply to a particular user.
from: matches any Tweet from a specific user.

So you probably want to use from instead of to
